# Generated by Django 4.2.1 on 2023-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='namaDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlevip', models.CharField(max_length=128)),
                ('namavip', models.CharField(max_length=64)),
                ('perusahaan', models.CharField(max_length=128)),
            ],
        ),
    ]
