# Generated by Django 4.2.1 on 2023-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namadisplay',
            name='jam',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
